<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Dineshs-MacBook-Pro.local" ignored="0" name="Test" tests="6" failures="2" timestamp="03 Mar 2019 04:31:34 GMT" time="3.684" errors="0">
  <testcase name="runScenario" time="1.609" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.671" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.241" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Status Check Passed - Supposed to be failed!!!">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Status Check Passed - Supposed to be failed!!!
at stepDefinition.test.checkResponseStatusIsNot200(test.java:71)
at ✽.I validate response is not successfull(file:src/test/resources/features/test.feature:36)
... Removed 1 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.326" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.313" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.284" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Status Check Passed - Supposed to be failed!!!">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Status Check Passed - Supposed to be failed!!!
at stepDefinition.test.checkResponseStatusIsNot200(test.java:71)
at ✽.I validate response is not successfull(file:src/test/resources/features/test2.feature:36)
... Removed 1 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Test -->
