<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Dineshs-MacBook-Pro.local" name="testRunners.TestRunner" tests="6" failures="2" timestamp="03 Mar 2019 04:02:31 GMT" time="3.757" errors="0">
  <testcase name="runScenario" time="0.288" classname="testRunners.TestRunner"/>
  <testcase name="runScenario" time="0.390" classname="testRunners.TestRunner">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Status Check Passed - Supposed to be failed!!!">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Status Check Passed - Supposed to be failed!!!
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at stepDefinition.test.checkResponseStatusIsNot200(test.java:71)
at ✽.I validate response is not successfull(file:src/test/resources/features/test2.feature:36)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.806" classname="testRunners.TestRunner"/>
  <testcase name="runScenario" time="0.315" classname="testRunners.TestRunner"/>
  <testcase name="runScenario" time="0.332" classname="testRunners.TestRunner">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Status Check Passed - Supposed to be failed!!!">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Status Check Passed - Supposed to be failed!!!
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at stepDefinition.test.checkResponseStatusIsNot200(test.java:71)
at ✽.I validate response is not successfull(file:src/test/resources/features/test.feature:36)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="1.626" classname="testRunners.TestRunner"/>
</testsuite> <!-- testRunners.TestRunner -->
